name = "example"
version = 1

[env]
VARIABLE = "Value" # Raw variable
EXPANSION = "$HOME/EXPAND" # Supports variable expansion. Does not expand variables declared in this section

[[steps]]
id = "my-first-step"
type = "shell" # Currently only supports shell commands
cmd = "echo 'Hello, World!'"
os = ["macos", "linux"] # you can omit this if you support both mac and linux

[[steps]]
id = "use-a-variable"
type = "shell"
cmd = 'echo $EXPANSION'

[[steps]]
id = "macos-only-step"
type = "shell"
cmd = "sw_vers"
os = ["macos"]

[[steps]]
id = "linux-only-step"
type = "shell"
cmd = "lsb_release -a"
os = ["linux"]
