name = "script-calling-recipe"
description = "Calls a script from the scripts directory"
author = "mise"
depends_on = ["example"] # We want to run this after the first greeting

[env]
RECIPE_MSG = "Invoked inside script"

[[steps]]
name = "call-script"
description = "calls a script inside the scripts directory and passes env variables"
cmd = "$SCRIPTS/example-script.sh"
os = ["macos", "linux"]
