//! Command-line interface definitions.
//!
//! This module uses [`clap`] derive macros to define the CLI structure,
//! including the main [`Cli`] parser and its subcommands in [`Command`].

use std::path::PathBuf;

use clap::{Parser, Subcommand};

/// Root CLI parser.
///
/// The parser is generated by [`clap`] using `derive(Parser)`.
#[derive(Debug, Parser)]
#[command(name = "mise", version, propagate_version = true)]
pub struct Cli {
    #[command(subcommand)]
    pub cmd: Option<Command>,
}

/// Top-level subcommands.
#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    /// Run a recipe or an entire cookbook.
    ///
    /// Without arguments, runs all recipes in the current directory’s cookbook.
    Run {
        /// Path to a cookbook directory (defaults to current directory).
        #[arg(default_value = "./")]
        cookbook_path: Option<PathBuf>,

        /// Path to a single recipe file to run.
        ///
        /// If specified, only this recipe will be executed.
        #[arg(short, long)]
        recipe: Option<PathBuf>,

        /// Continue running remaining steps/recipes even if one fails.
        #[arg(long, default_value_t = false)]
        continue_on_error: bool,
    },

    /// Initialize a new cookbook directory structure.
    ///
    /// Creates the standard subdirectories (`recipes/`, `scripts/`, etc.)
    /// and starter files (`README.md`, `config.toml`, examples).
    Init {
        /// Target path where the new cookbook will be created.
        #[arg(default_value = "./my-cookbook")]
        path: PathBuf,
    },

    /// Print an execution plan for a cookbook.
    ///
    /// Displays the cookbook’s metadata and recipes in dependency order,
    /// without executing any steps.
    Plan {
        /// Path to a cookbook directory.
        #[arg(default_value = "./")]
        cookbook_path: PathBuf,
    },
}
