//! Command-line interface definitions.
//!
//! This module uses [`clap`] derive macros to define the CLI structure,
//! including the main [`Cli`] parser and its subcommands in [`Command`].

use std::path::PathBuf;

use clap::{Parser, Subcommand};

use crate::logging::LogFormat;

/// Root CLI parser.
///
/// The parser is generated by [`clap`] using `derive(Parser)`.
#[derive(Debug, Parser)]
#[command(name = "prep", version, propagate_version = true)]
pub struct Cli {
    // ===== Global logging flags =====
    /// Log format: auto (default), pretty, compact, json
    #[arg(long, value_enum, default_value_t = LogFormat::Auto, global = true, env = "PREP_LOG_FORMAT")]
    pub log_format: LogFormat,

    /// Disable ANSI colors in logs
    #[arg(long, global = true, env = "PREP_NO_ANSI")]
    pub no_ansi: bool,

    /// Disable timestamps in logs
    #[arg(long, global = true, env = "PREP_NO_TIME")]
    pub no_time: bool,

    /// Send logs to stdout (default is stderr)
    #[arg(long, global = true, env = "PREP_LOG_TO_STDOUT")]
    pub log_to_stdout: bool,
    // =================================
    #[command(subcommand)]
    pub cmd: Option<Command>,
}

/// Top-level subcommands.
#[derive(Debug, Subcommand)]
pub(crate) enum Command {
    /// Initialize a new cookbook directory structure.
    ///
    /// Creates the standard subdirectories (`recipes/`, `scripts/`, etc.)
    /// and starter files (`README.md`, `config.toml`, examples).
    Init {
        /// Target path where the new cookbook will be created.
        #[arg(default_value = "./my-cookbook")]
        path: PathBuf,
    },

    /// Print an execution plan for a cookbook.
    ///
    /// Displays the cookbook’s metadata and recipes in dependency order,
    /// without executing any steps.
    Plan {
        /// Path to a cookbook directory.
        #[arg(default_value = "./")]
        cookbook_path: PathBuf,
    },

    /// Run a recipe or an entire cookbook.
    ///
    /// Without arguments, runs all recipes in the current directory’s cookbook.
    Run {
        /// Path to a cookbook directory (defaults to current directory).
        #[arg(default_value = "./")]
        cookbook_path: PathBuf,

        /// Path to a single recipe file to run.
        ///
        /// If specified, only this recipe will be executed.
        #[arg(short, long)]
        recipe: Option<PathBuf>,

        /// Continue running remaining steps/recipes even if one fails.
        #[arg(long, default_value_t = false)]
        continue_on_error: bool,
    },
}
